spring:
  application:
    name: inventory-service
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/inventory_db?authSource=admin
server:
  port: 8071